---
- name: check git version
  hosts: all 
  become: true 

  tasks:
    - name: git version need to check 
      ansible.builtin.command: git --version
      register: git_version

    - name: Display Git version
      ansible.builtin.debug:
        msg: "{{ git_version.stdout }}"

      
